### ISSUE TITLE
Clear rationale needed for Cleartext JWE not being simply JWE JSON Serialization

### ISSUE THREAD

**Issue by selfissued** [erdtman/Cleartext-JOSE#27]
If we're going to create a Cleartext JWE specification that does something different than the JWE JSON Serialization, we need a very good reason for doing so.  Furthermore, this reason needs to be put in the Introduction section of the Cleartext JWE specification, so that's available for public scrutiny and review.

I know that I was told once why we though we wanted to be different than the JWE JSON Serialization but I don't remember.  We need to write this down.

My default position on this is that unless the answer involves using ES6 canonicalization in places where JOSE currently uses base64url encoding, we're on pretty weak grounds advocating a different encryption representation.

**Comment by cyberphone** [comment]
Here is an example from RFC7516 using JWE JSON Serialization:
```json
{
  "protected": "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2In0",
  "unprotected": {
     "jku":"https://server.example.com/keys.jwks"
   },
  "header": {
    "alg":"A128KW",
    "kid":"7"
  },
  "encrypted_key": "6KB707dM9YTIgHtLvtgWQ8mKwboJW3of9locizkDTHzBC2IlrT1oOQ",
  "iv": "AxY8DCtDaGlsbGljb3RoZQ",
  "ciphertext": "KDlTtXchhZTGufMYmOYGS4HffxPSUrfmqCHXaI9wOGY",
  "tag": "Mz-VPPyU4RlcuYv1IwIvzw"
}
```
The same in Cleartext JWE Notation:
```json
{
  "enc":"A128CBC-HS256",
  "jku":"https://server.example.com/keys.jwks",
  "alg":"A128KW",
  "kid":"7",
  "encrypted_key": "6KB707dM9YTIgHtLvtgWQ8mKwboJW3of9locizkDTHzBC2IlrT1oOQ",
  "iv": "AxY8DCtDaGlsbGljb3RoZQ",
  "ciphertext": "KDlTtXchhZTGufMYmOYGS4HffxPSUrfmqCHXaI9wOGY",
  "tag": "Mz-VPPyU4RlcuYv1IwIvzw"
}
```
Differences:
- All header properties as well as `encrypted_key` are _protected_
- All header properties are supplied in _clear_
- Simple syntax, intended matching the Cleartext JWS counterpart

**Comment by selfissued** [comment]
Thanks for the reminder.  I remember that now.

I'll take a stab at writing statements for the introductions of both specs saying what they are and aren't doing.

By the way, if we could use the same examples as in JWS and JWE, but Cleartext-ify them, that would probably help people really understand the differences and why they're there.

**Comment by cyberphone** [comment]
> By the way, if we could use the same examples as in JWS and JWE, but Cleartext-ify them, that would probably help people really understand the differences and why they're there.

That would be cool but it isn't possible because JWS and Cleartext JWS have different heritages and primary target applications.  Putting this in the spec would be like a comparison which is "best" which we don't need or want.  There are though a few core characteristics worth mentioning:

<table><tr><th></th><th>JWS</th><th>Cleartext JWS</th></tr>
<tr><th>Data&nbsp;to&nbsp;be&nbsp;signed</th><td>Any&nbsp;type&nbsp;and&nbsp;format</td><td>Non-intrusive signature object for inclusion<br>in arbitrary JSON and JavaScript objects</td></tr>
<tr><th>Encoding&nbsp;of&nbsp;signed&nbsp;data</th><td>Base64Url</td><td>None</td></tr>
<tr><th>Encoding&nbsp;of&nbsp;header&nbsp;data</th><td>Base64Url</td><td>None</td></tr>
<tr><th>URL&nbsp;friendly</th><td>Core&nbsp;feature</td><td>Out of scope</td></tr>
</table>

&nbsp;<br>

### Out of scope for IETF documents
The table above is _deliberately a simplification_ since JWS also supports a "detached" mode but then we would enter very difficult discussions which won't lead us forward as the following scheme loosely derived from **Open&nbsp;Banking&nbsp;UK** shows:
```code
POST /payments HTTP/1.1
x-jws-signature: TGlmZSdzIGEgam91cm5 ... leSBhg6fttg6gh88bfxmlf5bdDrA3
Content-Type: application/json

{
  "amount": "259.99",
  "currency": "GBP"
}
```
This scheme has (_in my opinion NB_) a number of shortcomings like:
- Ties signatures to HTTP
- Does not permit signed objects to be _embedded_ in other objects
- Does not easily facilitate _serialization_ of signed data
- Shrouds header data in Base64Url

A Cleartext JWS counterpart would address all the issues above:
```code
POST /payments HTTP/1.1
Content-Type: application/json

{
  "amount": "259.99",
  "currency": "GBP",
  "__cleartext_signature": {
    "alg": "RS256",
    "kid": "#45233",
    "signature": "Mtqlw2PPUoZSO4DAHNzZ9gk_ ... z8HsK3fE1jux6jFVrrhwSZiRaW6M"
  }
}
```
For the crypto folks on the JOSE mailing list, these are essentially no-issues since they regard signatures as the "core".  For people designing systems (including myself....), signatures are rather "components" in an architecture.

**Comment by selfissued** [comment]
@cyberphone - thanks for the useful perspectives.  I think we should actually include a version of the table in your comment in the specifications so that people understand what the goals are and what they are not.  I believe that clearly defining the goals and non-goals will be key to success and acceptance of the project.

Can you create a PR to add the table to the spec or specs in the introductions?  Thanks!

**Comment by erdtman** [comment]
We have some of that already in the introduction

      Why not build directly on the JWE JSON Format? In the original JWE format
      all data that are to be protected needs to be
      base64url encoded, as a JSON format this becomes a contradiction in itself.
      In the JWE JSON format, base64url encoding only the parts that must be
      protected solves this (most of the data can then be JSON).  By serializing
      the JSON directly for protection it is more direct to serialize the whole
      package including, header parameters, recipients and the encrypted key than just the
      protected header part. Furthermore, this makes reasoning about the
package easier since the whole thing is protected (not just parts).

**Comment by selfissued** [comment]
I'll take an action item to work on the rationale sections in both of the specs.  I think that having clear rationale for both, and probably saying what's different than the existing JOSE specs and why, will be important to people deciding to support working on Cleartext JOSE specs, rather than opposing them.

**Comment by erdtman** [comment]
@selfissued I assume this was done in your cleanup PR
