### ISSUE TITLE
Global/Local Scope clarification/simplification 

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#6]
In the JWE variant `alg` may be specified at the top level as well as inside an `recipients` object.

I would prefer that `alg` either only exists at the top level or in the `recipients` objects rather than giving local definitions precedence.  Crypto should be strict :-)

My current implementation follows this idea but the code is quite simple anyway.

If preference order rather is to be honored, how should a non-referred `alg` be treated?

**Comment by erdtman** [comment]
Is there no preference order defined by JWE? If there are non I would like to do as you suggest if there are a defined preference order I would like us to add some text to make it more explicit so that it cannot be missed.

**Comment by selfissued** [comment]
Reusing the existing JOSE decisions, values like "alg" could be at either level when there are multiple parties, but not both.

**Comment by selfissued** [comment]
PR #32 addresses this for encryption.  Do we need additional text or changes to address this for signing?

**Comment by erdtman** [comment]
There is not such text in Cleartext JWS yet since it has not been yet been adopted to the structure we decided on with the 'signers' attribute. I expect it to reflect this text when written. see #1.

I think the PR can be merged and the issue closed. when solving issue #1 this should be part (I´ll add a comment)
