### ISSUE TITLE
IANA registration of the "signature" attribute

### ISSUE THREAD

**Issue by cyberphone** [erdtman/Cleartext-JOSE#9]
If you take a sharp look at the JWS variant, "signature" is technically only a label and thus does not motivate IANA registration.

However, deprecating "signature" would be going too far.

How about:
For maximum interoperability it is RECOMMENDED using "signature" to denote the presence of an enveloped signature sub object.

BTW, this further motivates the idea supporting multiple signatures in the same way as JWE deals with multiple encryption objects:  https://github.com/erdtman/Cleartext-JOSE/issues/1  That is, defining a _unified_ signature container _sub object_.  Please pardon my obsession with unification.

**Comment by erdtman** [comment]
Not sure I´m following.

I can see that section '7.2.1.  General JWS JSON Serialization Syntax' in JWS defines 'signature' and 'signatures' and that these have not been registered (I guess since they are not to be used in the same scope as alg, enc, etc.).

I do not see that we would need to register it either since that would be a general JOSN registry then since it will exist in application space.

Or an I completely of?

**Comment by cyberphone** [comment]
In case the unlikely clash with applications should be considered, may I propose a compromise?

`@signature`

This naming model seems quite popular among JSON folks for indicating "special" properties.  The `__signature` thing is a bit ugly in my taste.

**Comment by selfissued** [comment]
For better or worse, @ has taken on a common meaning as a Twitter handle prefix, such as @selfissued.  Therefore, we'd only create confusion by using it.

__ has a standard meaning as denoting a reserved word - for instance, see ANSI C.  I still think it's the right choice.

**Comment by cyberphone** [comment]
Hey ho, this is why I started with the naming issues :-)

FWIW, we wouldn't be alone using @ as an indicator for a reserved word:
https://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords

Anyway, my suggestion was really that `signature` (or `@signature`) would **not** be a reserved word, _only a recommendation_, giving folks that are into edge cases a reasonable "escape clause".

In the meantime I will dig a little bit into OpenAPI/Swagger to see how they deal with similar issues.

Question: Can we publish an initial I-D using `signature` with a comment that it may change?

**Comment by selfissued** [comment]
I'd rather come to a set of decisions that we all support before we publish an ID. I'll plan to look over everything in the next few days.

**Comment by cyberphone** [comment]
That is (of course) my and Samuel's wish as well.  It could be an idea scheduling a 1h Skype call.  I'm currently writing on a BOF proposal: https://github.com/erdtman/Cleartext-JOSE/blob/master/BOF.md

**Comment by cyberphone** [comment]
Another way of wording things:

```code
Signing a JSON object is accomplished by creating a signature object
according to this specification, residing behind an additional,
application defined, top level property.
```

This is pretty far from my original (2013) take on the matter which was heavily influenced by its XML "predecessor", but it should to be working anyway.

**Comment by cyberphone** [comment]
Since a signature object can be treated similar to other derived objects like dateTime or complex numbers, reserving a "signature" key word seems (in retrospect...) like a bad idea.   I have even in my own designs sometimes questioned myself why I couldn't use more intuitive names like `authorizationSignature`, `commitSignature`, `requestSignature` etc.   This would also be more logical for inclusion in schema-driven stuff like OpenAPI/Swagger.

**Comment by cyberphone** [comment]
Hum, by removing the label you could also sign JSON arrays but I would personally be a bit cautious about extending the specification for an "edge case":

&nbsp;&nbsp;&nbsp;&nbsp;`["hi", true, {}, 3, {`_Signature Object_`}]`

**Comment by erdtman** [comment]
I like the Idea of not defining a specific name for the signature object key.

In that way we avoid conflicts and I think it is reasonable to demand applications to know where to read the signature. Another reflection it that this would follow the pattern OAuth uses for endpoint paths, i.e. not demanding specific path but guiding by examples.

**Comment by erdtman** [comment]
and I would use the name 'signature' in the examples.

**Comment by selfissued** [comment]
Not using a specific name would hurt interop.  It's fine to have a default name and say that it can be different.  For instance, the "cnf" claim in RFC 7800 is like that.  But values should have names that are published and registered.  I was never against registering the names.  I just wasn't sure they were being registered in the right places, which is why I pulled the registrations for now.

**Comment by erdtman** [comment]
I agree a fixed name improves interoperability, but has the risk of name conflict since it will be placed in application context in this case.

I think 'cnf' and 'signature' in this case are slightly different. 'cnf' exists in a well defined namespace with registration of attributes so having a fixed name is easy. While 'signature' is intended to be placed in a very flexible application namespace. (I think this is similar to the OAuth situation with endpoints, token, authorize etc. that will have to exist in different web-applications)

How about defaulting to 'signature' and keeping the language open for implementations to use another name in case of conflict (or strong preferences)?

**Comment by selfissued** [comment]
The reason to use default names like __cleartext_signature is that conflicts will essentially never happen.  Conflicts are nearly guaranteed for some applications for the name "signature".  We should steer clear of it.

**Comment by selfissued** [comment]
Per our discussions on the 2-Feb-18 call, we will use __cleartext_signature as the default top-level name.

**Comment by selfissued** [comment]
IANA registrations for "signature" and "signers" are now present in the Cleartext JWS draft and "ciphertext", "encrypted_key", and "recipients" are now present in the Cleartext JWE draft.  I believe that this addresses the IANA registration issue.
